name: CI

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9'
    - name: Clear NPM cache
      run: npm cache clean --force
    - name: Install Dependencies
      run: npm install
    - name: Install Ionic CLI and vite
      run: |
        npm install vite
        npm install -g @ionic/cli
    - name: Start Server
      run: |
        cd apps/GABOR45
        ionic serve --no-open &
        sleep 10
    - name: Run Cypress tests
      run: |
        cd apps/GABOR45/
        npx cypress run
